deduplicated error handling

diff --git a/databases/postgres/jobs/db-new b/databases/postgres/jobs/db-new
--- a/databases/postgres/jobs/db-new
+++ b/databases/postgres/jobs/db-new
@@ -1,15 +1,14 @@
 #!/usr/bin/env bash
 
-FATAL_FILE="./fatal.txt"
-[ -f $FATAL_FILE ] && cat $FATAL_FILE && exit 1
+appgen-info || exit
 
-[ ! -f "./app-name" ] && echo "missing file: ./app-name" > "$FATAL_FILE" && cat "$FATAL_FILE" && exit 1
-DB_NAME=$(./app-name)"-database-1"
+[ ! -f "./_app_name" ] && echo "missing file: ./_app_name" > "$FATAL_FILE" && cat "$FATAL_FILE" && exit 1
+DB_NAME=$(./_app_name)"-database-1"
 
 mkdir -p ./backend/database/scripts
 
-echo "echo ${DB_NAME}" > ./backend/database/scripts/database-name
-chmod +x ./backend/database/scripts/database-name
+echo "echo ${DB_NAME}" > ./backend/database/scripts/_db_name
+chmod +x ./backend/database/scripts/_db_name
 
 echo "**/db_data" > .gitignore
 
